import 'dart:convert';
import 'dart:typed_data';

import 'package:flutter_test/flutter_test.dart';
import 'package:black_cat/src/app/errors/errors.dart';
import 'package:black_cat/src/app/tools/tools.dart';

final _now = DateTime(2026, 9, 16);

/// 2027-01-15 and 2026-01-15 in seconds
const _future = 1799971200;
const _past = 1768435200;

String _cookiesTxt({int expires = _future, bool session = true}) => [
  '# Netscape HTTP Cookie File',
  '# This file is generated by yt-dlp.  Do not edit.',
  '',
  [
    '.youtube.com',
    'TRUE',
    '/',
    'TRUE',
    '$expires',
    'PREF',
    'f6=40000000',
  ].join('\t'),
  if (session) ...[
    [
      '#HttpOnly_.youtube.com',
      'TRUE',
      '/',
      'TRUE',
      '$expires',
      'LOGIN_INFO',
      'AFmmF2sw:QUQ3MjNm',
    ].join('\t'),
    [
      '.youtube.com',
      'TRUE',
      '/',
      'TRUE',
      '$expires',
      'SAPISID',
      'sapisid-value',
    ].join('\t'),
  ],
  [
    '.google.com',
    'TRUE',
    '/',
    'TRUE',
    '$expires',
    'NID',
    'google-value',
  ].join('\t'),
  ['.example.com', 'TRUE', '/', 'FALSE', '$expires', 'tracker', 'x'].join('\t'),
].join('\n');

Uint8List _utf8(String text) => Uint8List.fromList(utf8.encode(text));

Matcher _failsWith(String code) => throwsA(
  isA<AuthenticationException>().having((error) => error.code, 'code', code),
);

void main() {
  const codes = AuthenticationErrorCodes();

  test('читает cookies YouTube и Google, чужие сайты отбрасывает', () {
    final cookies = CookiesFileParser.parse(
      _utf8(_cookiesTxt()),
      fileName: 'cookies.txt',
      now: _now,
    );

    expect(
      [for (final cookie in cookies) cookie.name],
      ['PREF', 'LOGIN_INFO', 'SAPISID', 'NID'],
    );
    expect(cookies[1].httpOnly, isTrue);
  });

  test(
    'понимает UTF-8 с BOM, UTF-16 из Блокнота и расширение в верхнем регистре',
    () {
      final text = _cookiesTxt();
      final utf16 = BytesBuilder()..add([0xFF, 0xFE]);

      for (final unit in text.codeUnits) {
        utf16.add([unit & 0xFF, unit >> 8]);
      }

      expect(
        CookiesFileParser.parse(
          Uint8List.fromList([0xEF, 0xBB, 0xBF, ..._utf8(text)]),
          fileName: 'c.TXT',
          now: _now,
        ),
        hasLength(4),
      );
      expect(
        CookiesFileParser.parse(utf16.toBytes(), fileName: 'c.txt', now: _now),
        hasLength(4),
      );
      expect(
        CookiesFileParser.parse(
          _utf8(text.replaceAll('\n', '\r\n')),
          fileName: 'c.txt',
          now: _now,
        ),
        hasLength(4),
      );
    },
  );

  test(
    'не текстовый файл: другое расширение, двоичные данные, битый UTF-8',
    () {
      expect(
        () => CookiesFileParser.parse(
          _utf8(_cookiesTxt()),
          fileName: 'cookies.sqlite',
          now: _now,
        ),
        _failsWith(codes.cookiesNotText),
      );
      expect(
        () => CookiesFileParser.parse(
          Uint8List.fromList([0x53, 0x51, 0x4C, 0x00, 0x01, 0x02]),
          fileName: 'c.txt',
        ),
        _failsWith(codes.cookiesNotText),
      );
      expect(
        () => CookiesFileParser.parse(
          Uint8List.fromList([0x41, 0xC3, 0x28]),
          fileName: 'c.txt',
        ),
        _failsWith(codes.cookiesNotText),
      );
    },
  );

  test('слишком большой файл отклоняется до разбора', () {
    expect(
      () => CookiesFileParser.parse(
        Uint8List(CookiesFileParser.maxFileBytes + 1),
        fileName: 'c.txt',
      ),
      _failsWith(codes.cookiesTooLarge),
    );
  });

  test('JSON и произвольный текст — не cookies.txt', () {
    expect(
      () => CookiesFileParser.parse(
        _utf8('[{"domain": ".youtube.com", "name": "SID"}]'),
        fileName: 'c.txt',
      ),
      _failsWith(codes.cookiesJson),
    );
    expect(
      () => CookiesFileParser.parse(
        _utf8('Список покупок\nмолоко, хлеб'),
        fileName: 'c.txt',
      ),
      _failsWith(codes.cookiesFormat),
    );
    expect(
      () => CookiesFileParser.parse(Uint8List(0), fileName: 'c.txt'),
      _failsWith(codes.cookiesFormat),
    );
  });

  test('нет cookies YouTube, нет входа, истёк срок', () {
    expect(
      () => CookiesFileParser.parse(
        _utf8(
          [
            '.example.com',
            'TRUE',
            '/',
            'FALSE',
            '$_future',
            'a',
            'b',
          ].join('\t'),
        ),
        fileName: 'c.txt',
        now: _now,
      ),
      _failsWith(codes.cookiesNoYouTube),
    );
    expect(
      () => CookiesFileParser.parse(
        _utf8(_cookiesTxt(session: false)),
        fileName: 'c.txt',
        now: _now,
      ),
      _failsWith(codes.cookiesNoSession),
    );
    expect(
      () => CookiesFileParser.parse(
        _utf8(_cookiesTxt(expires: _past)),
        fileName: 'c.txt',
        now: _now,
      ),
      _failsWith(codes.cookiesExpired),
    );
  });
}
